# Site settings
title: Rob McCormack
email: rob.cmm@gmail.com
description: "I'm a front-end developer at DIAS_. Based in Barcelona."
baseurl: ""
url: "http://pire.github.io"
twitter_username: p1r3
github_username:  pire

# Build settings
markdown: kramdown
permalink: pretty